import { getState, applyCloudSync } from './store.js';

// Cloud Sync lets several coaches share one team's setup and match data
// season-long, without this app growing a backend of its own. A Google
// Sheet (via a small Apps Script "Web App") stands in for a server: it's
// free, each team owns their own copy, and Google's own deploy flow is
// the only piece that genuinely can't be automated away from a static
// site like this one — everything else (generating the two access
// tokens, building the exact script to paste, assembling both share
// links) is done here so a coach never has to invent or hand-edit
// anything.
//
// Two roles, enforced by the Apps Script itself (see buildAppsScript
// below), not just by what this app's UI shows:
//   - "editor" (Full Edit): can push anything — team settings, roster,
//     matches.
//   - "matchday": can push match data and add brand-new players (e.g. a
//     late arrival), but the script silently ignores anything else a
//     Matchday-token request sends, no matter what this app posts. The
//     UI additionally hides those controls on a Matchday device (see
//     isMatchdayOnly, used by roster.js/settings.js) so an edit never
//     looks like it saved when it didn't.
// Training sessions and the Drill Library are NOT part of Cloud Sync at
// all — each coach's plans and drills stay entirely on their own device;
// pushToCloud never even sends them, so there's nothing for the shared
// Sheet to store or for another device to pick up.
//
// This device's own connection (which URL, which role, when it last
// synced) lives in its own localStorage key — deliberately separate from
// the synced team data in store.js, so it's never accidentally pushed to
// or pulled from the shared sheet. A Matchday device only ever learns its
// own link's role from the server; it never sees the Full Edit token.

const SYNC_CONFIG_KEY = 'ysg-cloud-sync-v1';

function loadConfig() {
  try {
    const raw = localStorage.getItem(SYNC_CONFIG_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch (e) {
    console.warn('Could not read Cloud Sync config', e);
    return null;
  }
}

function saveConfig(cfg) {
  try {
    localStorage.setItem(SYNC_CONFIG_KEY, JSON.stringify(cfg));
  } catch (e) {
    console.warn('Could not save Cloud Sync config', e);
  }
}

export function getSyncConfig() {
  return loadConfig();
}

export function isCloudSyncConnected() {
  return !!loadConfig();
}

// Used by roster.js, settings.js (Team/Rules), training.js, and drills.js
// to hide edit controls a Matchday device's pushes can't actually save —
// the Apps Script rejects those changes regardless, this just keeps the
// UI from implying they worked.
export function isMatchdayOnly() {
  const cfg = loadConfig();
  return !!cfg && cfg.role === 'matchday';
}

export function disconnectCloudSync() {
  try {
    localStorage.removeItem(SYNC_CONFIG_KEY);
  } catch (e) {
    console.warn('Could not clear Cloud Sync config', e);
  }
}

function randomToken() {
  if (window.crypto && window.crypto.randomUUID) {
    return window.crypto.randomUUID().replace(/-/g, '').slice(0, 20);
  }
  // Fallback for a browser without crypto.randomUUID — still plenty of
  // entropy for this threat model (a private link, not a login).
  return Array.from({ length: 20 }, () => Math.floor(Math.random() * 36).toString(36)).join('');
}

// The complete Google Apps Script source, with this team's two freshly
// generated tokens already baked in — a coach copies this exactly as-is,
// no editing required. This is the single source of truth for the
// script (rather than also keeping a separate reference copy in the
// repo, which would risk drifting out of sync with this one).
export function buildAppsScript({ fullEditToken, matchdayToken }) {
  return `// Boot Room Cloud Sync — paste this ENTIRE file into
// Extensions > Apps Script for a blank Google Sheet (delete anything
// already there first), then Deploy > New deployment > Web app
// (Execute as: Me, Who has access: Anyone), and paste the resulting
// URL back into Boot Room's Settings > Cloud Sync.
//
// These two tokens were generated by Boot Room for your team — don't
// edit them. The Full Edit token can change anything; the Matchday
// token can only push match data and add brand-new players.
var FULL_EDIT_TOKEN = '${fullEditToken}';
var MATCHDAY_TOKEN = '${matchdayToken}';

var SHEET_NAME = 'BootRoomData';
var CHUNK_COUNT_CELL = 'A1';
var META_CELL = 'B1';
// Google Sheets refuses to store more than 50,000 characters in a single
// cell — a real, hard platform limit, not a bug in this script. A team's
// combined team/roster/games JSON starts small but grows every match
// (especially the live-tracking detail on a completed game), and once it
// crosses that line, Range.setValue throws inside Apps Script. That kind
// of platform-level failure isn't always something this script's own
// try/catch can even see — the request can come back as an error page
// with no CORS header at all, which every browser then reports to the
// app as a bare, contentless network failure. Splitting the JSON across
// as many numbered cells as it takes (A2, A3, A4, ...) keeps every
// individual cell safely under the limit, so total storage scales with
// however many chunks are needed instead of stopping dead at 50,000
// characters.
var CHUNK_SIZE_ = 40000;

function getSheet_() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(SHEET_NAME);
  if (!sheet) sheet = ss.insertSheet(SHEET_NAME);
  return sheet;
}

function roleForToken_(token) {
  if (token === FULL_EDIT_TOKEN) return 'editor';
  if (token === MATCHDAY_TOKEN) return 'matchday';
  return null;
}

function jsonResponse_(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}

function readStored_() {
  var sheet = getSheet_();
  var chunkCount = parseInt(sheet.getRange(CHUNK_COUNT_CELL).getValue(), 10) || 0;
  var metaRaw = sheet.getRange(META_CELL).getValue();
  var meta = null;
  try {
    meta = metaRaw ? JSON.parse(metaRaw) : null;
  } catch (e) {
    meta = null;
  }
  if (!chunkCount) return { data: null, meta: meta };
  var parts = [];
  for (var i = 0; i < chunkCount; i++) {
    // Row 2 onward, column A — chunk 0 in A2, chunk 1 in A3, and so on.
    parts.push(sheet.getRange(2 + i, 1).getValue());
  }
  try {
    return { data: JSON.parse(parts.join('')), meta: meta };
  } catch (e) {
    return { data: null, meta: meta };
  }
}

function writeStored_(data, updatedBy) {
  var sheet = getSheet_();
  var json = JSON.stringify(data);
  var chunks = [];
  for (var i = 0; i < json.length; i += CHUNK_SIZE_) {
    chunks.push(json.slice(i, i + CHUNK_SIZE_));
  }
  var previousChunkCount = parseInt(sheet.getRange(CHUNK_COUNT_CELL).getValue(), 10) || 0;
  for (var k = 0; k < chunks.length; k++) {
    sheet.getRange(2 + k, 1).setValue(chunks[k]);
  }
  // Clear any chunk cells left over from a previous, longer write — the
  // new data is often shorter (e.g. after season archiving), and a stale
  // chunk past the new count would otherwise sit there unreferenced by
  // reads but never actually gone.
  for (var j = chunks.length; j < previousChunkCount; j++) {
    sheet.getRange(2 + j, 1).setValue('');
  }
  sheet.getRange(CHUNK_COUNT_CELL).setValue(chunks.length);
  sheet.getRange(META_CELL).setValue(JSON.stringify({ updatedAt: new Date().toISOString(), updatedBy: updatedBy || '' }));
}

// Same "how far along is this" score the app itself uses to pick between
// two copies of a game (store.js's gameCompleteness/gameIsNewer) — status
// first, then how much has actually been logged, then updatedAt as a
// last tiebreak. Without this check here, on the server, a push landing
// after someone else's is a BLIND overwrite of the whole games array —
// two coaches each running their own separate match and syncing normally
// throughout the day is exactly the case that hits this: whichever
// device's sync happens to land last would silently revert every OTHER
// match to whatever stale copy that device last knew about, even though
// the client-side merge (which only ever protects what a device pulls
// INTO itself) had nothing wrong with it. Merging here, at the one place
// every device's data actually lands, is the only way to stop a slower
// or earlier-started sync from clobbering a genuinely newer one.
var STATUS_RANK_ = { scheduled: 0, live: 1, completed: 2 };
function gameCompleteness_(g) {
  return (STATUS_RANK_[g.status] || 0) * 10000 + ((g.live && g.live.subLog && g.live.subLog.length) || 0);
}
function gameIsNewer_(incoming, existing) {
  var c1 = gameCompleteness_(incoming);
  var c2 = gameCompleteness_(existing);
  if (c1 !== c2) return c1 > c2;
  return (incoming.updatedAt || 0) > (existing.updatedAt || 0);
}
function isGameLike_(g) {
  return !!(g && typeof g === 'object');
}
function mergeGames_(currentGames, postedGames) {
  // A genuine game object without an id can't be merged by id at all —
  // carry it through unmerged rather than letting it collide with every
  // other id-less entry under the same "undefined" key, or throw trying
  // to compare it. Anything that isn't even an object at all (null, a
  // stray string) is just dropped rather than preserved forever.
  var validCurrent = (currentGames || []).filter(function (g) { return isGameLike_(g) && g.id; });
  var validPosted = (postedGames || []).filter(function (g) { return isGameLike_(g) && g.id; });
  var idless = (currentGames || []).concat(postedGames || []).filter(function (g) { return isGameLike_(g) && !g.id; });

  var byId = {};
  validCurrent.forEach(function (g) { byId[g.id] = g; });
  validPosted.forEach(function (incoming) {
    var existing = byId[incoming.id];
    if (!existing || gameIsNewer_(incoming, existing)) byId[incoming.id] = incoming;
  });
  var result = [];
  var seenIds = {};
  validPosted.forEach(function (g) {
    if (!seenIds[g.id]) { result.push(byId[g.id]); seenIds[g.id] = true; }
  });
  validCurrent.forEach(function (g) {
    if (!seenIds[g.id]) { result.push(byId[g.id]); seenIds[g.id] = true; }
  });
  return result.concat(idless);
}

// mergeGames_ deliberately never lets a game disappear just because one
// side's push didn't mention it — that's the whole point of it, and
// exactly why a deleted game used to come straight back on the next
// sync: there was no way to tell "deleted" apart from "this device never
// knew about it". A tombstone ({id, deletedAt}) is that explicit signal.
// Union two tombstone lists, keeping the later deletedAt for any id both
// sides know about.
function mergeDeletedGameIds_(current, posted) {
  var byId = {};
  (current || []).concat(posted || []).forEach(function (t) {
    if (!t || !t.id) return;
    if (!byId[t.id] || (t.deletedAt || 0) > (byId[t.id].deletedAt || 0)) byId[t.id] = t;
  });
  return Object.keys(byId).map(function (id) { return byId[id]; });
}

// Drops any merged game whose tombstone is at least as new as the game's
// own updatedAt — same "newer wins" principle as gameIsNewer_, just
// comparing against a plain deletion timestamp instead of another copy
// of the game. A game genuinely updated AFTER it was deleted elsewhere
// (someone resurrected/reused the match) survives; otherwise the
// deletion holds.
function applyTombstones_(games, tombstones) {
  var byId = {};
  (tombstones || []).forEach(function (t) { if (t && t.id) byId[t.id] = t; });
  return (games || []).filter(function (g) {
    var t = g && g.id && byId[g.id];
    if (!t) return true;
    return (g.updatedAt || 0) > (t.deletedAt || 0);
  });
}

// Every path through doGet/doPost must return valid JSON, never let an
// exception escape uncaught — an uncaught error makes Apps Script return
// its own HTML error response instead, which doesn't carry the CORS
// header a cross-origin fetch() needs. The browser then throws a plain
// network error, indistinguishable from a real connection problem, for
// what was actually a bug in this script. Wrapping every handler is what
// turns that into a visible, readable error instead.
function doGet(e) {
  try {
    var token = (e && e.parameter && e.parameter.token) || '';
    var role = roleForToken_(token);
    if (!role) return jsonResponse_({ error: 'Invalid or missing Cloud Sync link.' });
    var stored = readStored_();
    return jsonResponse_({ role: role, data: stored.data, meta: stored.meta });
  } catch (err) {
    return jsonResponse_({ error: 'Server error in doGet: ' + (err && err.message || String(err)) });
  }
}

function doPost(e) {
  try {
    var token = (e && e.parameter && e.parameter.token) || '';
    var role = roleForToken_(token);
    if (!role) return jsonResponse_({ error: 'Invalid or missing Cloud Sync link.' });

    var posted;
    try {
      posted = JSON.parse(e.postData.contents);
    } catch (err) {
      return jsonResponse_({ error: 'Malformed request.' });
    }
    if (!posted || !posted.team || !posted.players || !posted.games) {
      return jsonResponse_({ error: 'Expected team, players, and games.' });
    }

    var current = readStored_().data;
    var mergedTombstones = mergeDeletedGameIds_(current ? current.deletedGameIds : [], posted.deletedGameIds);
    var toStore;

    if (role === 'editor') {
      toStore = {
        team: posted.team,
        players: posted.players,
        games: applyTombstones_(mergeGames_(current ? current.games : [], posted.games), mergedTombstones),
        deletedGameIds: mergedTombstones,
      };
    } else {
      // Matchday: only games change, plus any brand-new players (e.g. a
      // late arrival). Team settings and edits/deletes to existing players
      // are never accepted from this token, no matter what was posted.
      if (!current) {
        return jsonResponse_({ error: 'No shared team data yet — ask the Full Edit coach to sync first.' });
      }
      var existingIds = {};
      (current.players || []).forEach(function (p) { existingIds[p.id] = true; });
      var newPlayers = (posted.players || []).filter(function (p) { return !existingIds[p.id]; });
      toStore = {
        team: current.team,
        players: (current.players || []).concat(newPlayers),
        games: applyTombstones_(mergeGames_(current.games, posted.games), mergedTombstones),
        deletedGameIds: mergedTombstones,
      };
    }

    writeStored_(toStore, posted.syncedByName || '');
    return jsonResponse_({ ok: true, role: role });
  } catch (err) {
    return jsonResponse_({ error: 'Server error in doPost: ' + (err && err.message || String(err)) });
  }
}
`;
}

// Uses XMLHttpRequest rather than fetch(). Google Apps Script's /exec URL
// always answers with a 302 to a script.googleusercontent.com URL that
// actually delivers the response body — WebKit (Safari, and every browser
// on iOS, since Apple requires them all to use WebKit under the hood) has
// a long-documented bug following that specific cross-origin redirect
// under fetch(), which surfaces as a plain "TypeError: Load failed" with
// no further detail, even though the exact same URL loads fine when
// pasted directly into the address bar (top-level navigation isn't
// subject to CORS at all, so it never hits this). XMLHttpRequest follows
// the same redirect through a different code path that isn't affected.
//
// Deliberately never sets a request header. A body sent as a plain string
// defaults to Content-Type "text/plain;charset=UTF-8" under both fetch()
// and XHR, which keeps this a CORS "simple request" — Google Apps Script
// Web Apps don't handle the preflight OPTIONS request a browser would
// otherwise send first for "application/json", so setting that header
// here would break every cross-origin POST. e.postData.contents on the
// script side gets the raw JSON text regardless of what Content-Type it
// was labeled with.
function callAppsScript(url, { method = 'GET', body } = {}) {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.timeout = 20000;
    xhr.open(method, url, true);
    xhr.onload = () => {
      if (xhr.status < 200 || xhr.status >= 300) {
        reject(new Error(`Cloud Sync returned an error (HTTP ${xhr.status}). The pasted script may need updating — see "Update Script" in Settings.`));
        return;
      }
      let parsedBody;
      try {
        parsedBody = JSON.parse(xhr.responseText);
      } catch (e) {
        reject(new Error('Cloud Sync returned something unexpected — double check the link was pasted in full.'));
        return;
      }
      if (parsedBody.error) {
        reject(new Error(parsedBody.error));
        return;
      }
      resolve(parsedBody);
    };
    // The previous version of this message discarded the real browser
    // error entirely, which made a genuine connection problem and a
    // server-side bug masquerading as one indistinguishable — naming what
    // actually happened here is the only way to tell them apart without
    // opening devtools. The payload size is included too: a tiny request
    // (like the diagnostic tool's probes) can succeed on a patchy mobile
    // connection while a much bigger one — a full team, roster, and a
    // whole match's worth of live events — drops mid-upload, so knowing
    // the size is what tells the two apart after the fact.
    const sizeNote = body ? ` — payload ~${Math.ceil(body.length / 1024)} KB` : '';
    xhr.onerror = () => {
      reject(new Error(`Could not reach Cloud Sync — check the link and your connection. (network error${sizeNote})`));
    };
    xhr.ontimeout = () => {
      reject(new Error(`Could not reach Cloud Sync — the request timed out. Check your connection and try again.${sizeNote}`));
    };
    xhr.send(body);
  });
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// A dropped connection or a slow upload over a patchy mobile connection —
// exactly the real-world condition on match day at a pitch with weak
// signal — fails a single attempt without Cloud Sync being genuinely
// unreachable. Retrying a couple of times, with a short pause so a
// momentary signal drop can clear, turns that into a non-issue instead of
// a hard failure. Never retries a clean error the script itself returned
// (a bad token, a validation failure) since sending the exact same
// request again can't fix those.
async function callAppsScriptWithRetries(url, options, attempts = 3) {
  for (let attempt = 1; attempt <= attempts; attempt++) {
    try {
      return await callAppsScript(url, options);
    } catch (e) {
      const retryable = /network error|timed out/.test(e.message);
      if (!retryable || attempt === attempts) {
        if (retryable && attempts > 1) e.message += ` [after ${attempt} attempt${attempt > 1 ? 's' : ''}]`;
        throw e;
      }
      await sleep(1500 * attempt);
    }
  }
}

// Browsers deliberately withhold *why* a cross-origin request failed
// (DNS, TLS, a dropped connection, and a CORS block all surface as the
// exact same generic error) — a privacy protection against sites
// fingerprinting someone's network, not a gap in this app's own error
// handling. This runs three probes to get past that ceiling:
//   1. The real Cloud Sync URL under mode: 'no-cors' — this only cares
//      whether the network connection itself completes, since a no-cors
//      response is never readable regardless of its headers. Succeeding
//      here despite the normal request failing pins the problem on CORS
//      headers specifically, not on connectivity.
//   2. The real Cloud Sync URL exactly as Sync Now requests it.
//   3. A well-known, definitely CORS-enabled external endpoint
//      (GitHub's own API) as a baseline — if even this fails, whatever's
//      wrong isn't specific to Google Apps Script, it's this device or
//      network blocking cross-origin requests generally.
export async function diagnoseCloudSyncConnection(url) {
  const lines = [];

  try {
    await fetch(url, { mode: 'no-cors' });
    lines.push('1. no-cors request to your Cloud Sync link: OK — a connection to Google was made.');
  } catch (e) {
    lines.push(`1. no-cors request to your Cloud Sync link: FAILED (${e.name}: ${e.message}) — the connection itself didn't complete.`);
  }

  try {
    const res = await fetch(url, { mode: 'cors' });
    lines.push(`2. Normal (CORS) request to your Cloud Sync link: OK — HTTP ${res.status}.`);
  } catch (e) {
    lines.push(`2. Normal (CORS) request to your Cloud Sync link: FAILED (${e.name}: ${e.message}).`);
  }

  try {
    const res = await fetch('https://api.github.com/zen', { mode: 'cors' });
    lines.push(`3. Baseline request to a well-known, unrelated site: OK — HTTP ${res.status}.`);
  } catch (e) {
    lines.push(`3. Baseline request to a well-known, unrelated site: FAILED (${e.name}: ${e.message}).`);
  }

  // Sync Now itself goes through XMLHttpRequest (see callAppsScript above),
  // not fetch() — if every probe above comes back clean but Sync Now still
  // fails, the difference is the transport, not the network or CORS, and
  // these two probes are the direct comparison.
  //
  // The POST probe sends `{}` rather than real data — the script rejects
  // that (missing team/players/games) before it ever writes anything (see
  // doPost in buildAppsScript above), so this exercises the exact same
  // network/CORS/transport path as a real push without touching any real
  // team data.
  const xhrProbe = (method, body) =>
    new Promise((resolve) => {
      const xhr = new XMLHttpRequest();
      xhr.timeout = 15000;
      xhr.open(method, url, true);
      xhr.onload = () => resolve(`OK — HTTP ${xhr.status}.`);
      xhr.onerror = () => resolve('FAILED (network error).');
      xhr.ontimeout = () => resolve('FAILED (timed out).');
      xhr.send(body);
    });
  lines.push(`4. XHR GET to your Cloud Sync link (what Sync Now itself uses to pull): ${await xhrProbe('GET')}`);
  lines.push(`5. XHR POST to your Cloud Sync link (what Sync Now itself uses to push): ${await xhrProbe('POST', JSON.stringify({}))}`);

  return lines.join('\n');
}

// GET only ever reads — both roles are allowed to see the full shared
// team, since the two-tier split here is about who can change things,
// not who can see them.
//
// The same URL gets fetched over and over (every sync pulls the exact
// same "?token=..." link) — exactly the shape a browser's HTTP cache (or
// a proxy sitting in between, e.g. on mobile data) heuristically caches a
// plain GET response for, since the Apps Script response carries no
// explicit Cache-Control header telling it not to. A device that hit a
// cached response would show every sync as "successful" while silently
// never seeing what anyone else has pushed since — indistinguishable from
// Cloud Sync being broken. Appending a timestamp guarantees this is never
// actually the same URL twice, so nothing (browser cache or an
// intermediate proxy) has a matching entry to serve back. It doesn't add
// a header, so this still qualifies as a CORS "simple request" (see
// callAppsScript).
export function pullFromCloud(url) {
  const bustedUrl = `${url}${url.includes('?') ? '&' : '?'}_ts=${Date.now()}`;
  return callAppsScriptWithRetries(bustedUrl, { method: 'GET' });
}

// POST always sends this device's team/roster/matches; the Apps Script
// itself decides how much of that actually gets written, based on which
// token the URL carries (see buildAppsScript above) — this file doesn't
// need to duplicate that logic, only trust the server to enforce it.
// Training sessions and drills are deliberately never included — see the
// comment near the top of this file.
export function pushToCloud(url, coachName) {
  const { team, players, games, deletedGameIds } = getState();
  return callAppsScriptWithRetries(url, {
    method: 'POST',
    body: JSON.stringify({ team, players, games, deletedGameIds: deletedGameIds || [], syncedByName: coachName || '' }),
  });
}

// Snapshots this device's current player list alongside the sync
// timestamp — applyCloudSync (store.js) compares a future pull against
// this to tell a genuinely unsynced local edit apart from a player it's
// already in step with, so pulling in the middle of a sync can't silently
// overwrite an edit that hasn't reached the cloud yet.
function markSynced() {
  const cfg = loadConfig();
  if (!cfg) return;
  const { players } = getState();
  saveConfig({ ...cfg, lastSyncedAt: new Date().toISOString(), lastSyncedPlayers: players });
}

// Generated once, up front, by the Settings modal — before the coach has
// even pasted their deploy URL — so the exact same pair can be baked into
// the script text they copy AND into the share links produced once setup
// finishes. Generating fresh tokens at the end instead would leave the
// two out of sync with whatever's actually pasted into Apps Script.
export function generateSyncTokens() {
  return { fullEditToken: randomToken(), matchdayToken: randomToken() };
}

// The Full Edit coach's own setup: saves this device's connection as
// "editor" using the tokens already baked into the script they deployed
// (see generateSyncTokens above), and seeds the sheet with this device's
// current data so a Matchday link handed out right afterward has
// something to pull. Returns the two ready-to-copy share links.
export async function setUpAsFullEditor(baseUrl, coachName, tokens) {
  const trimmedBase = baseUrl.trim().replace(/\/$/, '').replace(/\?.*$/, '');
  if (!trimmedBase) throw new Error('Paste the Web App URL Google gave you after deploying.');

  const { fullEditToken, matchdayToken } = tokens;
  const fullEditUrl = `${trimmedBase}?token=${fullEditToken}`;
  const matchdayUrl = `${trimmedBase}?token=${matchdayToken}`;

  saveConfig({ url: fullEditUrl, role: 'editor', coachName: coachName || '', baseUrl: trimmedBase, fullEditToken, matchdayToken, lastSyncedAt: null });
  await pushToCloud(fullEditUrl, coachName);
  markSynced();

  return { fullEditUrl, matchdayUrl };
}

// Connecting a device with a link someone else already gave you — the
// role comes back from the server (whichever token the link carries),
// never guessed client-side.
export async function joinWithLink(url, coachName) {
  const trimmedUrl = url.trim();
  if (!trimmedUrl) throw new Error('Paste the Cloud Sync link you were given.');

  const result = await pullFromCloud(trimmedUrl);
  saveConfig({ url: trimmedUrl, role: result.role, coachName: coachName || '', lastSyncedAt: new Date().toISOString(), lastServerMeta: result.meta || null });
  if (result.data) applyCloudSync(result.data);
  markSynced();
  return result;
}

// The everyday action once connected: pull first so this device has
// everyone else's latest before it pushes its own — otherwise a push
// from a device that's been offline a while could overwrite changes it
// never saw. Passing this device's own last-synced player snapshot into
// applyCloudSync is what keeps that pull from also overwriting an edit
// made on THIS device since — the push right after sends it up for real.
// Both directions best-effort; a network hiccup on either leg doesn't
// lose anything already saved locally.
export async function syncNow() {
  const cfg = loadConfig();
  if (!cfg) throw new Error('Cloud Sync isn\'t set up on this device yet.');

  const pulled = await pullFromCloud(cfg.url);
  const mergeResult = pulled.data ? applyCloudSync(pulled.data, cfg.lastSyncedPlayers) : null;
  // Captured from the PULL, before this device's own push below overwrites
  // it on the server — so it reflects whoever synced most recently before
  // this device, which is the useful "who else is syncing with me" signal
  // (a device just echoing its own last push back at itself isn't).
  if (pulled.meta) saveConfig({ ...cfg, lastServerMeta: pulled.meta });
  await pushToCloud(cfg.url, cfg.coachName);
  markSynced();
  return mergeResult;
}

// Best-effort, silent sync used for the automatic triggers (app load,
// match end) — errors are swallowed rather than shown, since a coach
// didn't explicitly ask for this one; "Sync Now" in Settings is where a
// failure gets surfaced so they can actually do something about it.
export async function syncSilently() {
  try {
    await syncNow();
    return true;
  } catch (e) {
    return false;
  }
}
