import { getState, applyCloudSync } from './store.js';

// Cloud Sync lets several coaches share one team's setup and match data
// season-long, without this app growing a backend of its own. A Google
// Sheet (via a small Apps Script "Web App") stands in for a server: it's
// free, each team owns their own copy, and Google's own deploy flow is
// the only piece that genuinely can't be automated away from a static
// site like this one — everything else (generating the two access
// tokens, building the exact script to paste, assembling both share
// links) is done here so a coach never has to invent or hand-edit
// anything.
//
// Two roles, enforced by the Apps Script itself (see buildAppsScript
// below), not just by what this app's UI shows:
//   - "editor" (Full Edit): can push anything — team settings, roster,
//     matches.
//   - "matchday": can push match data and add brand-new players (e.g. a
//     late arrival), but the script silently ignores anything else a
//     Matchday-token request sends, no matter what this app posts. The
//     UI additionally hides those controls on a Matchday device (see
//     isMatchdayOnly, used by roster.js/settings.js) so an edit never
//     looks like it saved when it didn't.
// Training sessions and the Drill Library are NOT part of Cloud Sync at
// all — each coach's plans and drills stay entirely on their own device;
// pushToCloud never even sends them, so there's nothing for the shared
// Sheet to store or for another device to pick up.
//
// This device's own connection (which URL, which role, when it last
// synced) lives in its own localStorage key — deliberately separate from
// the synced team data in store.js, so it's never accidentally pushed to
// or pulled from the shared sheet. A Matchday device only ever learns its
// own link's role from the server; it never sees the Full Edit token.

const SYNC_CONFIG_KEY = 'ysg-cloud-sync-v1';

function loadConfig() {
  try {
    const raw = localStorage.getItem(SYNC_CONFIG_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch (e) {
    console.warn('Could not read Cloud Sync config', e);
    return null;
  }
}

function saveConfig(cfg) {
  try {
    localStorage.setItem(SYNC_CONFIG_KEY, JSON.stringify(cfg));
  } catch (e) {
    console.warn('Could not save Cloud Sync config', e);
  }
}

export function getSyncConfig() {
  return loadConfig();
}

export function isCloudSyncConnected() {
  return !!loadConfig();
}

// Used by roster.js, settings.js (Team/Rules), training.js, and drills.js
// to hide edit controls a Matchday device's pushes can't actually save —
// the Apps Script rejects those changes regardless, this just keeps the
// UI from implying they worked.
export function isMatchdayOnly() {
  const cfg = loadConfig();
  return !!cfg && cfg.role === 'matchday';
}

export function disconnectCloudSync() {
  try {
    localStorage.removeItem(SYNC_CONFIG_KEY);
  } catch (e) {
    console.warn('Could not clear Cloud Sync config', e);
  }
}

function randomToken() {
  if (window.crypto && window.crypto.randomUUID) {
    return window.crypto.randomUUID().replace(/-/g, '').slice(0, 20);
  }
  // Fallback for a browser without crypto.randomUUID — still plenty of
  // entropy for this threat model (a private link, not a login).
  return Array.from({ length: 20 }, () => Math.floor(Math.random() * 36).toString(36)).join('');
}

// The complete Google Apps Script source, with this team's two freshly
// generated tokens already baked in — a coach copies this exactly as-is,
// no editing required. This is the single source of truth for the
// script (rather than also keeping a separate reference copy in the
// repo, which would risk drifting out of sync with this one).
export function buildAppsScript({ fullEditToken, matchdayToken }) {
  return `// Boot Room Cloud Sync — paste this ENTIRE file into
// Extensions > Apps Script for a blank Google Sheet (delete anything
// already there first), then Deploy > New deployment > Web app
// (Execute as: Me, Who has access: Anyone), and paste the resulting
// URL back into Boot Room's Settings > Cloud Sync.
//
// These two tokens were generated by Boot Room for your team — don't
// edit them. The Full Edit token can change anything; the Matchday
// token can only push match data and add brand-new players.
var FULL_EDIT_TOKEN = '${fullEditToken}';
var MATCHDAY_TOKEN = '${matchdayToken}';

var SHEET_NAME = 'BootRoomData';
var DATA_CELL = 'A1';
var META_CELL = 'B1';

function getSheet_() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(SHEET_NAME);
  if (!sheet) sheet = ss.insertSheet(SHEET_NAME);
  return sheet;
}

function roleForToken_(token) {
  if (token === FULL_EDIT_TOKEN) return 'editor';
  if (token === MATCHDAY_TOKEN) return 'matchday';
  return null;
}

function jsonResponse_(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}

function readStored_() {
  var sheet = getSheet_();
  var raw = sheet.getRange(DATA_CELL).getValue();
  var metaRaw = sheet.getRange(META_CELL).getValue();
  if (!raw) return { data: null, meta: null };
  try {
    return { data: JSON.parse(raw), meta: metaRaw ? JSON.parse(metaRaw) : null };
  } catch (e) {
    return { data: null, meta: null };
  }
}

function writeStored_(data, updatedBy) {
  var sheet = getSheet_();
  sheet.getRange(DATA_CELL).setValue(JSON.stringify(data));
  sheet.getRange(META_CELL).setValue(JSON.stringify({ updatedAt: new Date().toISOString(), updatedBy: updatedBy || '' }));
}

function doGet(e) {
  var token = (e && e.parameter && e.parameter.token) || '';
  var role = roleForToken_(token);
  if (!role) return jsonResponse_({ error: 'Invalid or missing Cloud Sync link.' });
  var stored = readStored_();
  return jsonResponse_({ role: role, data: stored.data, meta: stored.meta });
}

function doPost(e) {
  var token = (e && e.parameter && e.parameter.token) || '';
  var role = roleForToken_(token);
  if (!role) return jsonResponse_({ error: 'Invalid or missing Cloud Sync link.' });

  var posted;
  try {
    posted = JSON.parse(e.postData.contents);
  } catch (err) {
    return jsonResponse_({ error: 'Malformed request.' });
  }
  if (!posted || !posted.team || !posted.players || !posted.games) {
    return jsonResponse_({ error: 'Expected team, players, and games.' });
  }

  var current = readStored_().data;
  var toStore;

  if (role === 'editor') {
    toStore = posted;
  } else {
    // Matchday: only games change, plus any brand-new players (e.g. a
    // late arrival). Team settings and edits/deletes to existing players
    // are never accepted from this token, no matter what was posted.
    if (!current) {
      return jsonResponse_({ error: 'No shared team data yet — ask the Full Edit coach to sync first.' });
    }
    var existingIds = {};
    (current.players || []).forEach(function (p) { existingIds[p.id] = true; });
    var newPlayers = (posted.players || []).filter(function (p) { return !existingIds[p.id]; });
    toStore = {
      team: current.team,
      players: (current.players || []).concat(newPlayers),
      games: posted.games,
    };
  }

  writeStored_(toStore, posted.syncedByName || '');
  return jsonResponse_({ ok: true, role: role });
}
`;
}

// Deliberately never sets a Content-Type header. A fetch() body left as a
// plain string defaults to "text/plain;charset=UTF-8", which keeps this a
// CORS "simple request" — Google Apps Script Web Apps don't handle the
// preflight OPTIONS request a browser would otherwise send first for
// "application/json", so setting that header here would break every
// cross-origin POST. e.postData.contents on the script side gets the raw
// JSON text regardless of what Content-Type it was labeled with.
async function callAppsScript(url, options) {
  let res;
  try {
    res = await fetch(url, options);
  } catch (e) {
    throw new Error('Could not reach Cloud Sync — check the link and your connection.');
  }
  let body;
  try {
    body = await res.json();
  } catch (e) {
    throw new Error('Cloud Sync returned something unexpected — double check the link was pasted in full.');
  }
  if (body.error) throw new Error(body.error);
  return body;
}

// GET only ever reads — both roles are allowed to see the full shared
// team, since the two-tier split here is about who can change things,
// not who can see them.
export function pullFromCloud(url) {
  return callAppsScript(url, { method: 'GET' });
}

// POST always sends this device's team/roster/matches; the Apps Script
// itself decides how much of that actually gets written, based on which
// token the URL carries (see buildAppsScript above) — this file doesn't
// need to duplicate that logic, only trust the server to enforce it.
// Training sessions and drills are deliberately never included — see the
// comment near the top of this file.
export function pushToCloud(url, coachName) {
  const { team, players, games } = getState();
  return callAppsScript(url, {
    method: 'POST',
    body: JSON.stringify({ team, players, games, syncedByName: coachName || '' }),
  });
}

// Snapshots this device's current player list alongside the sync
// timestamp — applyCloudSync (store.js) compares a future pull against
// this to tell a genuinely unsynced local edit apart from a player it's
// already in step with, so pulling in the middle of a sync can't silently
// overwrite an edit that hasn't reached the cloud yet.
function markSynced() {
  const cfg = loadConfig();
  if (!cfg) return;
  const { players } = getState();
  saveConfig({ ...cfg, lastSyncedAt: new Date().toISOString(), lastSyncedPlayers: players });
}

// Generated once, up front, by the Settings modal — before the coach has
// even pasted their deploy URL — so the exact same pair can be baked into
// the script text they copy AND into the share links produced once setup
// finishes. Generating fresh tokens at the end instead would leave the
// two out of sync with whatever's actually pasted into Apps Script.
export function generateSyncTokens() {
  return { fullEditToken: randomToken(), matchdayToken: randomToken() };
}

// The Full Edit coach's own setup: saves this device's connection as
// "editor" using the tokens already baked into the script they deployed
// (see generateSyncTokens above), and seeds the sheet with this device's
// current data so a Matchday link handed out right afterward has
// something to pull. Returns the two ready-to-copy share links.
export async function setUpAsFullEditor(baseUrl, coachName, tokens) {
  const trimmedBase = baseUrl.trim().replace(/\/$/, '').replace(/\?.*$/, '');
  if (!trimmedBase) throw new Error('Paste the Web App URL Google gave you after deploying.');

  const { fullEditToken, matchdayToken } = tokens;
  const fullEditUrl = `${trimmedBase}?token=${fullEditToken}`;
  const matchdayUrl = `${trimmedBase}?token=${matchdayToken}`;

  saveConfig({ url: fullEditUrl, role: 'editor', coachName: coachName || '', baseUrl: trimmedBase, fullEditToken, matchdayToken, lastSyncedAt: null });
  await pushToCloud(fullEditUrl, coachName);
  markSynced();

  return { fullEditUrl, matchdayUrl };
}

// Connecting a device with a link someone else already gave you — the
// role comes back from the server (whichever token the link carries),
// never guessed client-side.
export async function joinWithLink(url, coachName) {
  const trimmedUrl = url.trim();
  if (!trimmedUrl) throw new Error('Paste the Cloud Sync link you were given.');

  const result = await pullFromCloud(trimmedUrl);
  saveConfig({ url: trimmedUrl, role: result.role, coachName: coachName || '', lastSyncedAt: new Date().toISOString(), lastServerMeta: result.meta || null });
  if (result.data) applyCloudSync(result.data);
  markSynced();
  return result;
}

// The everyday action once connected: pull first so this device has
// everyone else's latest before it pushes its own — otherwise a push
// from a device that's been offline a while could overwrite changes it
// never saw. Passing this device's own last-synced player snapshot into
// applyCloudSync is what keeps that pull from also overwriting an edit
// made on THIS device since — the push right after sends it up for real.
// Both directions best-effort; a network hiccup on either leg doesn't
// lose anything already saved locally.
export async function syncNow() {
  const cfg = loadConfig();
  if (!cfg) throw new Error('Cloud Sync isn\'t set up on this device yet.');

  const pulled = await pullFromCloud(cfg.url);
  const mergeResult = pulled.data ? applyCloudSync(pulled.data, cfg.lastSyncedPlayers) : null;
  // Captured from the PULL, before this device's own push below overwrites
  // it on the server — so it reflects whoever synced most recently before
  // this device, which is the useful "who else is syncing with me" signal
  // (a device just echoing its own last push back at itself isn't).
  if (pulled.meta) saveConfig({ ...cfg, lastServerMeta: pulled.meta });
  await pushToCloud(cfg.url, cfg.coachName);
  markSynced();
  return mergeResult;
}

// Best-effort, silent sync used for the automatic triggers (app load,
// match end) — errors are swallowed rather than shown, since a coach
// didn't explicitly ask for this one; "Sync Now" in Settings is where a
// failure gets surfaced so they can actually do something about it.
export async function syncSilently() {
  try {
    await syncNow();
    return true;
  } catch (e) {
    return false;
  }
}
