// A curated starting set of real, publicly published youth soccer drills a
// coach can load in one click via "Load Starter Drill Pack" on the Drill
// Library screen. Each entry links to a genuine coaching video rather than
// shipping any binary attachment, so the pack stays tiny and never eats
// into a device's localStorage headroom. Descriptions are original
// summaries, not copied from the linked source. ageGroups uses the same
// six bands as ageFormats.js (see PRESET_AGE_GROUPS in views/drills.js).
export const STARTER_DRILLS = [
  // Warm-up
  { name: 'Passing Warm-Up Drill', description: 'A short, structured passing sequence to open a session — gets players moving the ball and communicating before anything more demanding.', link: 'https://www.youtube.com/watch?v=iXOF18rS2D0', tags: ['Warm-up', 'Passing'], ageGroups: ['U8-U9', 'U10-U11'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 160\" width=\"300\" height=\"160\"><rect width=\"300\" height=\"160\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"144\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><circle cx=\"40\" cy=\"30\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"40\" cy=\"80\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"40\" cy=\"130\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"260\" cy=\"30\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"260\" cy=\"80\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"260\" cy=\"130\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><line x1=\"50\" y1=\"80\" x2=\"250\" y2=\"80\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"250,80 242.6,83.1 242.6,76.9\" fill=\"#ffffff\"/><text x=\"150\" y=\"150\" font-size=\"11\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">Pass across, jog to back of opposite line</text></svg>" },
  { name: 'Passing & Dribbling Warm-Up (5 Variations)', description: 'Five linked warm-up variations mixing passing and dribbling, so a coach can rotate through them across a season without repeating the same opener.', link: 'https://www.youtube.com/watch?v=2WmImvXDHVY', tags: ['Warm-up', 'Passing', 'Dribbling & Ball Control'], ageGroups: ['U10-U11', 'U12', 'U13'] },
  { name: 'Fun Warm-Up Games', description: 'Playful, game-based warm-ups aimed at younger players — keeps energy and engagement high while still raising heart rates before training.', link: 'https://www.youtube.com/watch?v=JSI-yeoH7C0', tags: ['Warm-up', 'Fun / Game-based'], ageGroups: ['U7', 'U8-U9'] },
  { name: 'Traffic Jam Warm-Up Game', description: 'A tag-style dribbling game where players weave through a crowded space without colliding — builds close control and spatial awareness in a fun format.', link: 'https://www.youtube.com/watch?v=SZE0dAdNqlo', tags: ['Warm-up', 'Fun / Game-based'], ageGroups: ['U7', 'U8-U9'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 180\" width=\"300\" height=\"180\"><rect width=\"300\" height=\"180\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"164\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><polygon points=\"50,31 44,45 56,45\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><polygon points=\"120,51 114,65 126,65\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><polygon points=\"200,26 194,40 206,40\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><polygon points=\"250,81 244,95 256,95\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><polygon points=\"80,111 74,125 86,125\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><polygon points=\"160,131 154,145 166,145\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><polygon points=\"230,141 224,155 236,155\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><polygon points=\"40,141 34,155 46,155\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><circle cx=\"100\" cy=\"90\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"190\" cy=\"100\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><text x=\"150\" y=\"170\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">Dribble freely, weave between cones without colliding</text></svg>" },

  // Passing
  { name: '10 Best Passing Drills', description: 'A rundown of ten passing exercises ranging from simple pairs work up to combination play, useful for building a progressive passing session.', link: 'https://www.youtube.com/watch?v=Kb58F3r_TQM', tags: ['Passing'], ageGroups: ['U8-U9', 'U10-U11', 'U12'] },
  { name: 'Triangle Passing: Movement & Third Man Run', description: 'Three players pass around a triangle shape while a fourth times a run off the ball — introduces the "third man" concept alongside basic passing accuracy.', link: 'https://www.youtube.com/watch?v=w8PbZQHf83M', tags: ['Passing'], ageGroups: ['U10-U11', 'U12', 'U13'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 190\" width=\"300\" height=\"190\"><rect width=\"300\" height=\"190\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"174\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><circle cx=\"150\" cy=\"35\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><text x=\"150\" y=\"39\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">A</text><circle cx=\"60\" cy=\"150\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><text x=\"60\" y=\"154\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">B</text><circle cx=\"240\" cy=\"150\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><text x=\"240\" y=\"154\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">C</text><circle cx=\"150\" cy=\"100\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><text x=\"150\" y=\"104\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">3</text><line x1=\"140\" y1=\"45\" x2=\"70\" y2=\"140\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"70,140 71.9,132.2 76.9,135.9\" fill=\"#ffffff\"/><line x1=\"70\" y1=\"150\" x2=\"230\" y2=\"150\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"230,150 222.6,153.1 222.6,146.9\" fill=\"#ffffff\"/><line x1=\"230\" y1=\"140\" x2=\"160\" y2=\"45\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"160,45 166.9,49.1 161.9,52.8\" fill=\"#ffffff\"/><text x=\"150\" y=\"180\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">Pass and rotate; third man times a run into the middle</text></svg>" },
  { name: 'Pass & Move Combination', description: 'Players pass and immediately move into space to receive again, reinforcing the habit of moving after a pass rather than watching the ball.', link: 'https://www.youtube.com/watch?v=EDJKPs2Qcag', tags: ['Passing'], ageGroups: ['U8-U9', 'U10-U11', 'U12'] },
  { name: 'Pass & Move Perfection', description: 'A follow-up passing sequence that layers in first-touch direction and quicker decision-making once the basic pass-and-move pattern is solid.', link: 'https://www.youtube.com/watch?v=YjxyntcEjl4', tags: ['Passing'], ageGroups: ['U8-U9', 'U10-U11', 'U12'] },
  { name: 'Receiving and Turning', description: 'A simple receive-and-turn exercise for younger players, focused on checking shoulders and opening the body before the ball arrives.', link: 'https://www.youtube.com/watch?v=oBT0UlLlFlQ', tags: ['Passing'], ageGroups: ['U7', 'U8-U9'] },

  // Dribbling & Ball Control
  { name: 'U10 Dribbling Drills', description: 'A set of dribbling exercises pitched at U10 level, covering close control and changes of direction at a pace suited to that age.', link: 'https://www.youtube.com/watch?v=RukcQggHAZU', tags: ['Dribbling & Ball Control'], ageGroups: ['U10-U11'] },
  { name: '10 Best Dribbling Drills', description: 'Ten dribbling exercises for younger age groups, each focused on a specific skill (cuts, drags, speed dribbling) that can be run as its own station.', link: 'https://www.youtube.com/watch?v=eD2T5GXeaYE', tags: ['Dribbling & Ball Control'], ageGroups: ['U7', 'U8-U9', 'U10-U11'] },
  { name: 'Ball Mastery Compilation', description: 'A compilation of ball-mastery moves (toe taps, rolls, cuts) that can be run individually or strung together as a longer warm-up circuit.', link: 'https://www.youtube.com/watch?v=xtyDeFwvltA', tags: ['Dribbling & Ball Control'], ageGroups: ['U8-U9', 'U10-U11', 'U12'] },
  { name: 'Complete Technical Training: Ball Mastery, Dribbling, Turning', description: 'A longer, twelve-exercise technical session combining ball mastery, dribbling and turning work — well suited as a full training-block template for older age groups.', link: 'https://www.youtube.com/watch?v=Yp4k6eSGgWw', tags: ['Dribbling & Ball Control'], ageGroups: ['U12', 'U13', 'U14+'] },

  // Shooting
  { name: '4-Cone Shooting Drill', description: 'Players receive from one of four marked cones and strike on goal, adding a decision-making element (which cone, which angle) to a basic shooting drill.', link: 'https://www.youtube.com/watch?v=nA6DKYOhO54', tags: ['Shooting'], ageGroups: ['U10-U11', 'U12', 'U13'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 190\" width=\"300\" height=\"190\"><rect width=\"300\" height=\"190\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"174\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><polygon points=\"60,31 54,45 66,45\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><polygon points=\"240,31 234,45 246,45\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><polygon points=\"60,131 54,145 66,145\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><polygon points=\"240,131 234,145 246,145\" fill=\"#f76707\" stroke=\"#ffffff\" stroke-width=\"0.75\"/><rect x=\"120\" y=\"10\" width=\"60\" height=\"14\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><circle cx=\"150\" cy=\"170\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><line x1=\"150\" y1=\"160\" x2=\"150\" y2=\"60\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"150,60 153.1,67.4 146.9,67.4\" fill=\"#ffffff\"/><text x=\"150\" y=\"185\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">Receive from a called cone, first touch, strike on goal</text></svg>" },
  { name: 'U6-U8 Shooting Drill', description: 'A simple, low-pressure shooting drill designed for the youngest age groups, prioritising contact and technique over accuracy or power.', link: 'https://www.youtube.com/watch?v=umPwPtVTbfY', tags: ['Shooting'], ageGroups: ['U7', 'U8-U9'] },
  { name: '5 Essential Shooting Drills', description: 'Five shooting exercises covering the basics players need to finish reliably — first-time strikes, placement, and shooting under a defender.', link: 'https://www.youtube.com/watch?v=CVF_qsuac6E', tags: ['Shooting'], ageGroups: ['U10-U11', 'U12', 'U13', 'U14+'] },

  // Defending
  { name: '1v1 Defending Drills', description: 'A block of 1v1 defending exercises focused on body position, patience, and timing the tackle rather than diving in.', link: 'https://www.youtube.com/watch?v=ceMFekk-xdE', tags: ['Defending'], ageGroups: ['U10-U11', 'U12'] },
  { name: '3 Best 1v1 Drills', description: 'Three fast-paced 1v1 exercises that put both attacker and defender under repeated pressure — useful as a short, high-intensity session block.', link: 'https://www.youtube.com/watch?v=5dCgkhnedPk', tags: ['Defending'], ageGroups: ['U10-U11', 'U12', 'U13'] },
  { name: 'Rotating 1v1 Defending Drill', description: 'A queue-based 1v1 defending drill where players rotate through attacker and defender roles, keeping numbers working continuously without long waits.', link: 'https://www.youtube.com/watch?v=7bWP2Ygwm_o', tags: ['Defending'], ageGroups: ['U12', 'U13', 'U14+'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 190\" width=\"300\" height=\"190\"><rect width=\"300\" height=\"190\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"174\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><rect x=\"110\" y=\"20\" width=\"80\" height=\"14\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><circle cx=\"150\" cy=\"100\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><text x=\"150\" y=\"104\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">A</text><circle cx=\"150\" cy=\"140\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><text x=\"150\" y=\"144\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">D</text><circle cx=\"60\" cy=\"160\" r=\"10\" fill=\"#868e96\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"100\" cy=\"170\" r=\"10\" fill=\"#868e96\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"200\" cy=\"170\" r=\"10\" fill=\"#868e96\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"240\" cy=\"160\" r=\"10\" fill=\"#868e96\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><line x1=\"150\" y1=\"140\" x2=\"150\" y2=\"60\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"150,60 153.1,67.4 146.9,67.4\" fill=\"#ffffff\"/><text x=\"150\" y=\"185\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">Attacker vs defender to goal; winner/loser rotate out</text></svg>" },
  { name: "Don't Dive In: 1v1 Defending", description: 'A drill built specifically around the common fault of defenders committing to a tackle too early — rewards patience and jockeying instead.', link: 'https://www.youtube.com/watch?v=uVkpeXS6Byw', tags: ['Defending'], ageGroups: ['U10-U11', 'U12'] },
  { name: '10 Best Defending Drills', description: 'Ten defending exercises spanning individual 1v1 work through to small-group defensive shape, suitable for building a full defending-themed session.', link: 'https://www.youtube.com/watch?v=MDF6tB5foI0', tags: ['Defending'], ageGroups: ['U8-U9', 'U10-U11', 'U12'] },

  // Possession / Rondo
  { name: '8v3 Rondo', description: 'A classic large-group rondo — eight players keep possession against three, sharpening quick passing and pressing triggers for the defenders.', link: 'https://www.youtube.com/watch?v=9jQRQsnyfKw', tags: ['Possession / Rondo'], ageGroups: ['U10-U11', 'U12', 'U13'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 190\" width=\"300\" height=\"190\"><rect width=\"300\" height=\"190\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"174\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><circle cx=\"150\" cy=\"95\" r=\"70\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><circle cx=\"220\" cy=\"95\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"199.49747468305833\" cy=\"144.49747468305833\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"150\" cy=\"165\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"100.50252531694167\" cy=\"144.49747468305833\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"80\" cy=\"95.00000000000001\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"100.50252531694167\" cy=\"45.50252531694168\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"150\" cy=\"25\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"199.49747468305833\" cy=\"45.502525316941664\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"130\" cy=\"85\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"165\" cy=\"100\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"150\" cy=\"115\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><text x=\"150\" y=\"180\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">8 outside keep possession; 3 inside press to win it back</text></svg>" },
  { name: 'Double Square Rondo', description: 'A rondo variation using two connected squares, adding a passing-range and decision-making layer on top of standard possession play.', link: 'https://www.youtube.com/watch?v=D2vHV6dMvqo', tags: ['Possession / Rondo'], ageGroups: ['U10-U11', 'U12', 'U13', 'U14+'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 190\" width=\"300\" height=\"190\"><rect width=\"300\" height=\"190\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"174\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><rect x=\"30\" y=\"30\" width=\"110\" height=\"110\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><rect x=\"160\" y=\"30\" width=\"110\" height=\"110\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><circle cx=\"30\" cy=\"30\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"140\" cy=\"30\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"30\" cy=\"140\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"140\" cy=\"140\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"160\" cy=\"30\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"270\" cy=\"30\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"160\" cy=\"140\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"270\" cy=\"140\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"85\" cy=\"85\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"215\" cy=\"85\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><line x1=\"140\" y1=\"85\" x2=\"160\" y2=\"85\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"160,85 152.6,88.1 152.6,81.9\" fill=\"#ffffff\"/><text x=\"150\" y=\"175\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">Two linked rondos; switch the ball between squares</text></svg>" },
  { name: 'Over The River Possession', description: 'Two teams keep possession in a zone split by a "river" the ball cannot be played through directly, forcing switches of play and patience.', link: 'https://www.youtube.com/watch?v=ATfIAwc5iLw', tags: ['Possession / Rondo'], ageGroups: ['U10-U11', 'U12', 'U13'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 180\" width=\"300\" height=\"180\"><rect width=\"300\" height=\"180\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"164\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><rect x=\"8\" y=\"80\" width=\"284\" height=\"20\" fill=\"#1c7ed6\" opacity=\"0.6\"/><circle cx=\"50\" cy=\"40\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"110\" cy=\"50\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"170\" cy=\"35\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"230\" cy=\"45\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"50\" cy=\"140\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"110\" cy=\"130\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"170\" cy=\"145\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"230\" cy=\"135\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><line x1=\"110\" y1=\"50\" x2=\"110\" y2=\"130\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"110,130 106.9,122.6 113.1,122.6\" fill=\"#ffffff\"/><text x=\"150\" y=\"170\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">Keep possession; the ball must cross the \"river\" by a pass</text></svg>" },
  { name: 'Pressing + Possession Drill', description: 'Combines possession-keeping with an active pressing team, so players practise both retaining the ball under pressure and organising a press to win it back.', link: 'https://www.youtube.com/watch?v=T0zkMg0ftgs', tags: ['Possession / Rondo'], ageGroups: ['U10-U11', 'U12', 'U13'] },

  // Small-Sided Games
  { name: 'Flip The Pitch', description: 'A small-sided game where scoring in either direction is live, encouraging quick transitions and discouraging players from switching off after losing the ball.', link: 'https://www.youtube.com/watch?v=tj-19D9bXQw', tags: ['Small-Sided Games'], ageGroups: ['U10-U11', 'U12', 'U13'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 170\" width=\"300\" height=\"170\"><rect width=\"300\" height=\"170\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"154\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><rect x=\"8\" y=\"70\" width=\"14\" height=\"30\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><rect x=\"278\" y=\"70\" width=\"14\" height=\"30\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><circle cx=\"80\" cy=\"50\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"150\" cy=\"40\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"80\" cy=\"120\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"220\" cy=\"50\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"150\" cy=\"120\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"220\" cy=\"120\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><line x1=\"150\" y1=\"40\" x2=\"260\" y2=\"85\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"260,85 252.0,85.1 254.4,79.3\" fill=\"#ffffff\"/><text x=\"150\" y=\"160\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">Both goals live — score, then transition to attack the other end</text></svg>" },
  { name: 'Small-Sided Games: 5 Variations', description: 'Five small-sided game formats a coach can rotate through in one session, each emphasising a slightly different in-game problem.', link: 'https://www.youtube.com/watch?v=9ojC_3pd-3k', tags: ['Small-Sided Games'], ageGroups: ['U8-U9', 'U10-U11', 'U12'] },
  { name: 'Power of Three', description: 'A small-sided game built around groups of three, rewarding combination play and quick support rather than individual dribbling.', link: 'https://www.youtube.com/watch?v=RtiRDRWaXNY', tags: ['Small-Sided Games'], ageGroups: ['U10-U11', 'U12'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 180\" width=\"300\" height=\"180\"><rect width=\"300\" height=\"180\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"164\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><circle cx=\"50\" cy=\"40\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"80\" cy=\"80\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"50\" cy=\"120\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"150\" cy=\"40\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"180\" cy=\"80\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"150\" cy=\"120\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"250\" cy=\"40\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"250\" cy=\"120\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><line x1=\"80\" y1=\"80\" x2=\"150\" y2=\"40\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"150,40 145.1,46.4 142.1,41.0\" fill=\"#ffffff\"/><line x1=\"180\" y1=\"80\" x2=\"250\" y2=\"80\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"250,80 242.6,83.1 242.6,76.9\" fill=\"#ffffff\"/><text x=\"150\" y=\"165\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">Groups of three combine to keep and progress the ball</text></svg>" },
  { name: 'Small-Sided Games for Penetrating Passes', description: 'A small-sided format with scoring conditions that specifically reward forward, penetrating passes rather than safe sideways possession.', link: 'https://www.youtube.com/watch?v=oNYEqlRwvs8', tags: ['Small-Sided Games'], ageGroups: ['U12', 'U13', 'U14+'] },
  { name: 'Attacking Small-Sided Game', description: 'A small-sided game weighted toward the attacking team, giving forwards extra practice creating and finishing chances against a set defence.', link: 'https://www.youtube.com/watch?v=wu3bGcvzt2s', tags: ['Small-Sided Games'], ageGroups: ['U10-U11', 'U12', 'U13'] },

  // Fitness & Conditioning
  { name: 'Agility Speed Ladder Drills', description: 'Speed-ladder footwork patterns aimed at youth players, building coordination and quick feet without any ball involved.', link: 'https://www.youtube.com/watch?v=WmewYBj2duY', tags: ['Fitness & Conditioning'], ageGroups: ['U10-U11', 'U12', 'U13', 'U14+'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 140\" width=\"300\" height=\"140\"><rect width=\"300\" height=\"140\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"124\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><rect x=\"40\" y=\"40\" width=\"20\" height=\"60\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><rect x=\"68\" y=\"40\" width=\"20\" height=\"60\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><rect x=\"96\" y=\"40\" width=\"20\" height=\"60\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><rect x=\"124\" y=\"40\" width=\"20\" height=\"60\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><rect x=\"152\" y=\"40\" width=\"20\" height=\"60\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><rect x=\"180\" y=\"40\" width=\"20\" height=\"60\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><rect x=\"208\" y=\"40\" width=\"20\" height=\"60\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><rect x=\"236\" y=\"40\" width=\"20\" height=\"60\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><circle cx=\"30\" cy=\"70\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><line x1=\"45\" y1=\"70\" x2=\"260\" y2=\"70\" stroke=\"#ffffff\" stroke-width=\"2\" /><polygon points=\"260,70 252.6,73.1 252.6,66.9\" fill=\"#ffffff\"/><text x=\"150\" y=\"120\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">Quick-feet patterns through each ladder rung</text></svg>" },
  { name: 'Fast Feet Training Drills', description: 'A set of quick-feet conditioning drills that double as a fun activation exercise before moving on to ball work.', link: 'https://www.youtube.com/watch?v=Ft4u3i6WftU', tags: ['Fitness & Conditioning'], ageGroups: ['U10-U11', 'U12', 'U13'] },
  { name: 'Best Agility Drills', description: 'A collection of cone- and ladder-based agility drills for improving change of direction, useful as a short conditioning block within a session.', link: 'https://www.youtube.com/watch?v=uW-CQtKoMdA', tags: ['Fitness & Conditioning'], ageGroups: ['U10-U11', 'U12', 'U13', 'U14+'] },
  { name: '16 Fitness Drills', description: 'Sixteen conditioning exercises covering speed, agility and endurance — a useful reference for building a standalone fitness session for older age groups.', link: 'https://www.youtube.com/watch?v=3fcuQGdhGjk', tags: ['Fitness & Conditioning'], ageGroups: ['U12', 'U13', 'U14+'] },

  // Goalkeeping
  { name: 'Reaction Training, Angles, and Ready Position', description: 'Goalkeeper-specific work on the ready position, closing down angles, and reacting quickly to shots — core fundamentals for any keeper.', link: 'https://www.youtube.com/watch?v=58eZb2reR94', tags: ['Goalkeeping'], ageGroups: ['U10-U11', 'U12', 'U13', 'U14+'] },
  { name: 'Top Drill for Goalkeepers', description: 'A single focused exercise for young goalkeepers, aimed at building handling confidence in a low-pressure, repetition-based setting.', link: 'https://www.youtube.com/watch?v=R64Fz8qX7UQ', tags: ['Goalkeeping'], ageGroups: ['U8-U9', 'U10-U11'] },
  { name: '7 Fun Goalkeeper Drills for Kids', description: 'Seven playful goalkeeping games aimed at the youngest keepers, keeping the position fun rather than isolating them from the rest of training.', link: 'https://www.youtube.com/watch?v=BHsPdQ7EnZM', tags: ['Goalkeeping'], ageGroups: ['U7', 'U8-U9', 'U10-U11'] },
  { name: '1v1 With Goalkeeper(s)', description: 'A competitive 1v1-to-goal exercise with a keeper included, so both the attacker’s finishing and the keeper’s shot-stopping get live repetitions together.', link: 'https://www.youtube.com/watch?v=hqCDeWmvxgI', tags: ['Goalkeeping', 'Small-Sided Games'], ageGroups: ['U10-U11', 'U12'] },
  { name: '9 Essential Goalkeeping Skills', description: 'A broader run-through of nine core goalkeeping skills, useful as a reference session plan for a keeper-specific training day with older players.', link: 'https://www.youtube.com/watch?v=k1i6kWXi2Ls', tags: ['Goalkeeping'], ageGroups: ['U12', 'U13', 'U14+'] },

  // Set Pieces
  { name: 'Smarter Free Kicks', description: 'Coaching points and set patterns for taking free kicks with more purpose, aimed at helping young players make better decisions rather than just striking hard.', link: 'https://www.youtube.com/watch?v=8vnZ7N4rT9E', tags: ['Set Pieces'], ageGroups: ['U12', 'U13', 'U14+'] },
  { name: 'Offensive Corner Kick Techniques', description: 'A look at attacking corner-kick routines and near-post/far-post runs, giving a team a couple of repeatable options rather than an unplanned scramble.', link: 'https://www.youtube.com/watch?v=RuMB38FSIdU', tags: ['Set Pieces'], ageGroups: ['U12', 'U13', 'U14+'] },
  { name: 'Corner Kicks at U9/U10 (7v7)', description: 'Corner-kick routines simplified for the smaller 7v7 format typical at U9/U10, keeping the pattern easy to remember for younger players.', link: 'https://www.youtube.com/watch?v=KcJEITSMxLY', tags: ['Set Pieces'], ageGroups: ['U8-U9', 'U10-U11'], diagramSvg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 190\" width=\"300\" height=\"190\"><rect width=\"300\" height=\"190\" fill=\"#2f9e44\" rx=\"10\"/><rect x=\"8\" y=\"8\" width=\"284\" height=\"174\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" rx=\"6\" opacity=\"0.85\"/><rect x=\"8\" y=\"70\" width=\"16\" height=\"30\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\"/><circle cx=\"20\" cy=\"30\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><text x=\"20\" y=\"34\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">K</text><circle cx=\"70\" cy=\"60\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"90\" cy=\"100\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"60\" cy=\"130\" r=\"10\" fill=\"#1971c2\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"75\" cy=\"80\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><circle cx=\"95\" cy=\"120\" r=\"10\" fill=\"#e8590c\" stroke=\"#ffffff\" stroke-width=\"1.5\"/><line x1=\"20\" y1=\"30\" x2=\"70\" y2=\"60\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"70,60 62.1,58.9 65.3,53.5\" fill=\"#ffffff\"/><line x1=\"20\" y1=\"30\" x2=\"60\" y2=\"130\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-dasharray=\"5,4\"/><polygon points=\"60,130 54.4,124.3 60.2,122.0\" fill=\"#ffffff\"/><text x=\"150\" y=\"175\" font-size=\"10\" font-family=\"sans-serif\" fill=\"#ffffff\" text-anchor=\"middle\">Near-post run and far-post run off a simple corner routine</text></svg>" },

  // Cool-down
  { name: 'Post-Training Cool-Down', description: 'A short, low-intensity cool-down routine to close out a session — light movement and stretching to bring heart rates back down before players head home.', link: 'https://www.youtube.com/watch?v=60Zr3pn69iM', tags: ['Cool-down'], ageGroups: ['U7', 'U8-U9', 'U10-U11', 'U12', 'U13', 'U14+'] },

  // Fun / Game-based
  { name: '100 Fun Training Ideas', description: 'A large reference list of fun, game-based training ideas — handy for a coach looking to swap in a fresh activity without repeating the same few games every week.', link: 'https://www.youtube.com/watch?v=hdrmEnoSMWw', tags: ['Fun / Game-based'], ageGroups: ['U7', 'U8-U9', 'U10-U11'] },
  { name: 'Fun Drills For Kids (Volume 2)', description: 'A second round-up of light, game-based drills for the youngest players, prioritising enjoyment and repeated ball touches over structured tactics.', link: 'https://www.youtube.com/watch?v=RpHv9vQ4wXI', tags: ['Fun / Game-based'], ageGroups: ['U7', 'U8-U9'] },
  { name: '5 Fun Soccer Drills for Kids', description: 'Five simple, playful drills pitched at the very youngest players, built around games rather than isolated technical repetition.', link: 'https://www.youtube.com/watch?v=s0WW2U-OStI', tags: ['Fun / Game-based'], ageGroups: ['U7'] },
];
